services:
  churn-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: churn-api

    ports:
      - "8000:8000"

    volumes:
      - ./data:/app/data
      - ./models:/app/models

    restart: unless-stopped